### ISSUE TITLE
Acknowledgements

### ISSUE THREAD

**Issue by tatiana-boura** [OliverWong258/Solving-3SAT-with-GTN#1]
Hey! Nice adjustments to the code. However, I think some acknowledgment is required. It would be nice to add the link  [(SAT-Solver-using-NNs)](https://github.com/tatiana-boura/SAT-Solver-using-NNs/tree/main) to the original project repository in the README, or at least give it a star. Thanks!

**Comment by OliverWong258** [comment]
Hello! I've been busy with other course projects and forgot to add the acknowledgement. I'll add it soon. Sorry about that.












Oliver
***@***.***


---Original---
From: "Tatiana ***@***.***&gt;
Date: Tue, Jan 23, 2024 18:37 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [OliverWong258/Solving-3SAT-with-GTN] Acknowledgements (Issue #1)




 
Hey! Nice adjustments to the code. However, I think some acknowledgment is required. It would be nice to add the link  (SAT-Solver-using-NNs) to the original project repository in the README, or at least give it a star. Thanks!

**Comment by tatiana-boura** [comment]
No worries, keep it up!
